# Generated by Django 4.2 on 2023-04-29 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middle_class_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedianHouseholdIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(max_length=7)),
                ('name', models.TextField()),
                ('median_hh_income', models.IntegerField()),
                ('moe', models.IntegerField()),
                ('year', models.IntegerField()),
                ('geography_name', models.CharField(max_length=10)),
                ('state_name', models.CharField(max_length=25)),
                ('state_fips', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('state_abb', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('geography_code', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
